// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/viniciuscluna/tc-fiap-50/internal/order/domain/entities"
	commands "github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockGetOrderStatusUseCase is an autogenerated mock type for the GetOrderStatusUseCase type
type MockGetOrderStatusUseCase struct {
	mock.Mock
}

type MockGetOrderStatusUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetOrderStatusUseCase) EXPECT() *MockGetOrderStatusUseCase_Expecter {
	return &MockGetOrderStatusUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockGetOrderStatusUseCase) Execute(command *commands.GetOrderStatusCommand) (*entities.OrderStatusEntity, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.OrderStatusEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*commands.GetOrderStatusCommand) (*entities.OrderStatusEntity, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(*commands.GetOrderStatusCommand) *entities.OrderStatusEntity); ok {
		r0 = rf(command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderStatusEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*commands.GetOrderStatusCommand) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetOrderStatusUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetOrderStatusUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.GetOrderStatusCommand
func (_e *MockGetOrderStatusUseCase_Expecter) Execute(command interface{}) *MockGetOrderStatusUseCase_Execute_Call {
	return &MockGetOrderStatusUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockGetOrderStatusUseCase_Execute_Call) Run(run func(command *commands.GetOrderStatusCommand)) *MockGetOrderStatusUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.GetOrderStatusCommand))
	})
	return _c
}

func (_c *MockGetOrderStatusUseCase_Execute_Call) Return(_a0 *entities.OrderStatusEntity, _a1 error) *MockGetOrderStatusUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetOrderStatusUseCase_Execute_Call) RunAndReturn(run func(*commands.GetOrderStatusCommand) (*entities.OrderStatusEntity, error)) *MockGetOrderStatusUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetOrderStatusUseCase creates a new instance of MockGetOrderStatusUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetOrderStatusUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetOrderStatusUseCase {
	mock := &MockGetOrderStatusUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
