// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/viniciuscluna/tc-fiap-50/internal/order/domain/entities"
	commands "github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockGetOrderUseCase is an autogenerated mock type for the GetOrderUseCase type
type MockGetOrderUseCase struct {
	mock.Mock
}

type MockGetOrderUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetOrderUseCase) EXPECT() *MockGetOrderUseCase_Expecter {
	return &MockGetOrderUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockGetOrderUseCase) Execute(command *commands.GetOrderCommand) (*entities.OrderEntity, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*commands.GetOrderCommand) (*entities.OrderEntity, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(*commands.GetOrderCommand) *entities.OrderEntity); ok {
		r0 = rf(command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*commands.GetOrderCommand) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetOrderUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetOrderUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.GetOrderCommand
func (_e *MockGetOrderUseCase_Expecter) Execute(command interface{}) *MockGetOrderUseCase_Execute_Call {
	return &MockGetOrderUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockGetOrderUseCase_Execute_Call) Run(run func(command *commands.GetOrderCommand)) *MockGetOrderUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.GetOrderCommand))
	})
	return _c
}

func (_c *MockGetOrderUseCase_Execute_Call) Return(_a0 *entities.OrderEntity, _a1 error) *MockGetOrderUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetOrderUseCase_Execute_Call) RunAndReturn(run func(*commands.GetOrderCommand) (*entities.OrderEntity, error)) *MockGetOrderUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetOrderUseCase creates a new instance of MockGetOrderUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetOrderUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetOrderUseCase {
	mock := &MockGetOrderUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
