// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/viniciuscluna/tc-fiap-50/internal/order/domain/entities"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// AddOrder provides a mock function with given fields: order
func (_m *MockOrderRepository) AddOrder(order *entities.OrderEntity) (*entities.OrderEntity, error) {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 *entities.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.OrderEntity) (*entities.OrderEntity, error)); ok {
		return rf(order)
	}
	if rf, ok := ret.Get(0).(func(*entities.OrderEntity) *entities.OrderEntity); ok {
		r0 = rf(order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.OrderEntity) error); ok {
		r1 = rf(order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_AddOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrder'
type MockOrderRepository_AddOrder_Call struct {
	*mock.Call
}

// AddOrder is a helper method to define mock.On call
//   - order *entities.OrderEntity
func (_e *MockOrderRepository_Expecter) AddOrder(order interface{}) *MockOrderRepository_AddOrder_Call {
	return &MockOrderRepository_AddOrder_Call{Call: _e.mock.On("AddOrder", order)}
}

func (_c *MockOrderRepository_AddOrder_Call) Run(run func(order *entities.OrderEntity)) *MockOrderRepository_AddOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.OrderEntity))
	})
	return _c
}

func (_c *MockOrderRepository_AddOrder_Call) Return(_a0 *entities.OrderEntity, _a1 error) *MockOrderRepository_AddOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_AddOrder_Call) RunAndReturn(run func(*entities.OrderEntity) (*entities.OrderEntity, error)) *MockOrderRepository_AddOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: orderId
func (_m *MockOrderRepository) GetOrder(orderId uint) (*entities.OrderEntity, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *entities.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.OrderEntity, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.OrderEntity); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - orderId uint
func (_e *MockOrderRepository_Expecter) GetOrder(orderId interface{}) *MockOrderRepository_GetOrder_Call {
	return &MockOrderRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", orderId)}
}

func (_c *MockOrderRepository_GetOrder_Call) Run(run func(orderId uint)) *MockOrderRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOrderRepository_GetOrder_Call) Return(_a0 *entities.OrderEntity, _a1 error) *MockOrderRepository_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetOrder_Call) RunAndReturn(run func(uint) (*entities.OrderEntity, error)) *MockOrderRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function with no fields
func (_m *MockOrderRepository) GetOrders() ([]*entities.OrderEntity, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 []*entities.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.OrderEntity, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.OrderEntity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockOrderRepository_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
func (_e *MockOrderRepository_Expecter) GetOrders() *MockOrderRepository_GetOrders_Call {
	return &MockOrderRepository_GetOrders_Call{Call: _e.mock.On("GetOrders")}
}

func (_c *MockOrderRepository_GetOrders_Call) Run(run func()) *MockOrderRepository_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderRepository_GetOrders_Call) Return(_a0 []*entities.OrderEntity, _a1 error) *MockOrderRepository_GetOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetOrders_Call) RunAndReturn(run func() ([]*entities.OrderEntity, error)) *MockOrderRepository_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
