// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/viniciuscluna/tc-fiap-50/internal/order/domain/entities"
	dto "github.com/viniciuscluna/tc-fiap-50/internal/order/infrastructure/api/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderPresenter is an autogenerated mock type for the OrderPresenter type
type MockOrderPresenter struct {
	mock.Mock
}

type MockOrderPresenter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderPresenter) EXPECT() *MockOrderPresenter_Expecter {
	return &MockOrderPresenter_Expecter{mock: &_m.Mock}
}

// Present provides a mock function with given fields: order
func (_m *MockOrderPresenter) Present(order *entities.OrderEntity) *dto.GetOrderResponseDto {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Present")
	}

	var r0 *dto.GetOrderResponseDto
	if rf, ok := ret.Get(0).(func(*entities.OrderEntity) *dto.GetOrderResponseDto); ok {
		r0 = rf(order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrderResponseDto)
		}
	}

	return r0
}

// MockOrderPresenter_Present_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Present'
type MockOrderPresenter_Present_Call struct {
	*mock.Call
}

// Present is a helper method to define mock.On call
//   - order *entities.OrderEntity
func (_e *MockOrderPresenter_Expecter) Present(order interface{}) *MockOrderPresenter_Present_Call {
	return &MockOrderPresenter_Present_Call{Call: _e.mock.On("Present", order)}
}

func (_c *MockOrderPresenter_Present_Call) Run(run func(order *entities.OrderEntity)) *MockOrderPresenter_Present_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.OrderEntity))
	})
	return _c
}

func (_c *MockOrderPresenter_Present_Call) Return(_a0 *dto.GetOrderResponseDto) *MockOrderPresenter_Present_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderPresenter_Present_Call) RunAndReturn(run func(*entities.OrderEntity) *dto.GetOrderResponseDto) *MockOrderPresenter_Present_Call {
	_c.Call.Return(run)
	return _c
}

// PresentMultipleStatus provides a mock function with given fields: orderStatus
func (_m *MockOrderPresenter) PresentMultipleStatus(orderStatus []*entities.OrderStatusEntity) []*dto.GetOrderStatusResponseDto {
	ret := _m.Called(orderStatus)

	if len(ret) == 0 {
		panic("no return value specified for PresentMultipleStatus")
	}

	var r0 []*dto.GetOrderStatusResponseDto
	if rf, ok := ret.Get(0).(func([]*entities.OrderStatusEntity) []*dto.GetOrderStatusResponseDto); ok {
		r0 = rf(orderStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.GetOrderStatusResponseDto)
		}
	}

	return r0
}

// MockOrderPresenter_PresentMultipleStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresentMultipleStatus'
type MockOrderPresenter_PresentMultipleStatus_Call struct {
	*mock.Call
}

// PresentMultipleStatus is a helper method to define mock.On call
//   - orderStatus []*entities.OrderStatusEntity
func (_e *MockOrderPresenter_Expecter) PresentMultipleStatus(orderStatus interface{}) *MockOrderPresenter_PresentMultipleStatus_Call {
	return &MockOrderPresenter_PresentMultipleStatus_Call{Call: _e.mock.On("PresentMultipleStatus", orderStatus)}
}

func (_c *MockOrderPresenter_PresentMultipleStatus_Call) Run(run func(orderStatus []*entities.OrderStatusEntity)) *MockOrderPresenter_PresentMultipleStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*entities.OrderStatusEntity))
	})
	return _c
}

func (_c *MockOrderPresenter_PresentMultipleStatus_Call) Return(_a0 []*dto.GetOrderStatusResponseDto) *MockOrderPresenter_PresentMultipleStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderPresenter_PresentMultipleStatus_Call) RunAndReturn(run func([]*entities.OrderStatusEntity) []*dto.GetOrderStatusResponseDto) *MockOrderPresenter_PresentMultipleStatus_Call {
	_c.Call.Return(run)
	return _c
}

// PresentOrders provides a mock function with given fields: orders
func (_m *MockOrderPresenter) PresentOrders(orders []*entities.OrderEntity) *dto.GetOrdersResponseDto {
	ret := _m.Called(orders)

	if len(ret) == 0 {
		panic("no return value specified for PresentOrders")
	}

	var r0 *dto.GetOrdersResponseDto
	if rf, ok := ret.Get(0).(func([]*entities.OrderEntity) *dto.GetOrdersResponseDto); ok {
		r0 = rf(orders)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrdersResponseDto)
		}
	}

	return r0
}

// MockOrderPresenter_PresentOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresentOrders'
type MockOrderPresenter_PresentOrders_Call struct {
	*mock.Call
}

// PresentOrders is a helper method to define mock.On call
//   - orders []*entities.OrderEntity
func (_e *MockOrderPresenter_Expecter) PresentOrders(orders interface{}) *MockOrderPresenter_PresentOrders_Call {
	return &MockOrderPresenter_PresentOrders_Call{Call: _e.mock.On("PresentOrders", orders)}
}

func (_c *MockOrderPresenter_PresentOrders_Call) Run(run func(orders []*entities.OrderEntity)) *MockOrderPresenter_PresentOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*entities.OrderEntity))
	})
	return _c
}

func (_c *MockOrderPresenter_PresentOrders_Call) Return(_a0 *dto.GetOrdersResponseDto) *MockOrderPresenter_PresentOrders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderPresenter_PresentOrders_Call) RunAndReturn(run func([]*entities.OrderEntity) *dto.GetOrdersResponseDto) *MockOrderPresenter_PresentOrders_Call {
	_c.Call.Return(run)
	return _c
}

// PresentProducts provides a mock function with given fields: orderProducts
func (_m *MockOrderPresenter) PresentProducts(orderProducts []*entities.OrderProductEntity) []*dto.OrderProductDto {
	ret := _m.Called(orderProducts)

	if len(ret) == 0 {
		panic("no return value specified for PresentProducts")
	}

	var r0 []*dto.OrderProductDto
	if rf, ok := ret.Get(0).(func([]*entities.OrderProductEntity) []*dto.OrderProductDto); ok {
		r0 = rf(orderProducts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.OrderProductDto)
		}
	}

	return r0
}

// MockOrderPresenter_PresentProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresentProducts'
type MockOrderPresenter_PresentProducts_Call struct {
	*mock.Call
}

// PresentProducts is a helper method to define mock.On call
//   - orderProducts []*entities.OrderProductEntity
func (_e *MockOrderPresenter_Expecter) PresentProducts(orderProducts interface{}) *MockOrderPresenter_PresentProducts_Call {
	return &MockOrderPresenter_PresentProducts_Call{Call: _e.mock.On("PresentProducts", orderProducts)}
}

func (_c *MockOrderPresenter_PresentProducts_Call) Run(run func(orderProducts []*entities.OrderProductEntity)) *MockOrderPresenter_PresentProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*entities.OrderProductEntity))
	})
	return _c
}

func (_c *MockOrderPresenter_PresentProducts_Call) Return(_a0 []*dto.OrderProductDto) *MockOrderPresenter_PresentProducts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderPresenter_PresentProducts_Call) RunAndReturn(run func([]*entities.OrderProductEntity) []*dto.OrderProductDto) *MockOrderPresenter_PresentProducts_Call {
	_c.Call.Return(run)
	return _c
}

// PresentStatus provides a mock function with given fields: orderStatus
func (_m *MockOrderPresenter) PresentStatus(orderStatus *entities.OrderStatusEntity) *dto.GetOrderStatusResponseDto {
	ret := _m.Called(orderStatus)

	if len(ret) == 0 {
		panic("no return value specified for PresentStatus")
	}

	var r0 *dto.GetOrderStatusResponseDto
	if rf, ok := ret.Get(0).(func(*entities.OrderStatusEntity) *dto.GetOrderStatusResponseDto); ok {
		r0 = rf(orderStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrderStatusResponseDto)
		}
	}

	return r0
}

// MockOrderPresenter_PresentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresentStatus'
type MockOrderPresenter_PresentStatus_Call struct {
	*mock.Call
}

// PresentStatus is a helper method to define mock.On call
//   - orderStatus *entities.OrderStatusEntity
func (_e *MockOrderPresenter_Expecter) PresentStatus(orderStatus interface{}) *MockOrderPresenter_PresentStatus_Call {
	return &MockOrderPresenter_PresentStatus_Call{Call: _e.mock.On("PresentStatus", orderStatus)}
}

func (_c *MockOrderPresenter_PresentStatus_Call) Run(run func(orderStatus *entities.OrderStatusEntity)) *MockOrderPresenter_PresentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.OrderStatusEntity))
	})
	return _c
}

func (_c *MockOrderPresenter_PresentStatus_Call) Return(_a0 *dto.GetOrderStatusResponseDto) *MockOrderPresenter_PresentStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderPresenter_PresentStatus_Call) RunAndReturn(run func(*entities.OrderStatusEntity) *dto.GetOrderStatusResponseDto) *MockOrderPresenter_PresentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderPresenter creates a new instance of MockOrderPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderPresenter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderPresenter {
	mock := &MockOrderPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
