with-expecter: true
mockname: "Mock{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/viniciuscluna/tc-fiap-50/internal/order/domain/repositories:
    config:
      dir: "mocks/order/domain/repositories"
      outpkg: mocks
    interfaces:
      OrderRepository:
      OrderProductRepository:
      OrderStatusRepository:
  github.com/viniciuscluna/tc-fiap-50/internal/infrastructure/clients:
    config:
      dir: "mocks/infrastructure/clients"
      outpkg: mocks
    interfaces:
      CustomerClient:
      ProductClient:
  github.com/viniciuscluna/tc-fiap-50/internal/shared/httpclient:
    config:
      dir: "mocks/shared/httpclient"
      outpkg: mocks
    interfaces:
      HTTPClient:
  github.com/viniciuscluna/tc-fiap-50/internal/order/presenter:
    config:
      dir: "mocks/order/presenter"
      outpkg: mocks
    interfaces:
      OrderPresenter:
  github.com/viniciuscluna/tc-fiap-50/internal/order/controller:
    config:
      dir: "mocks/order/controller"
      outpkg: mocks
    interfaces:
      OrderController:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/addOrder:
    config:
      dir: "mocks/order/usecase/addOrder"
      outpkg: mocks
    interfaces:
      AddOrderUseCase:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/getOrder:
    config:
      dir: "mocks/order/usecase/getOrder"
      outpkg: mocks
    interfaces:
      GetOrderUseCase:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/getOrders:
    config:
      dir: "mocks/order/usecase/getOrders"
      outpkg: mocks
    interfaces:
      GetOrdersUseCase:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/getOrderStatus:
    config:
      dir: "mocks/order/usecase/getOrderStatus"
      outpkg: mocks
    interfaces:
      GetOrderStatusUseCase:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/updateOrderStatus:
    config:
      dir: "mocks/order/usecase/updateOrderStatus"
      outpkg: mocks
    interfaces:
      UpdateOrderStatusUseCase:
