with-expecter: true
dir: "tests/mocks"
all: true
inpackage: false
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/viniciuscluna/tc-fiap-50/internal/order/domain/repositories:
    interfaces:
      OrderRepository:
      OrderProductRepository:
      OrderStatusRepository:
  github.com/viniciuscluna/tc-fiap-50/internal/infrastructure/clients:
    interfaces:
      CustomerClient:
      ProductClient:
  github.com/viniciuscluna/tc-fiap-50/internal/shared/httpclient:
    interfaces:
      HTTPClient:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/addOrder:
    interfaces:
      AddOrderUseCase:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/getOrder:
    interfaces:
      GetOrderUseCase:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/getOrders:
    interfaces:
      GetOrdersUseCase:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/getOrderStatus:
    interfaces:
      GetOrderStatusUseCase:
  github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/updateOrderStatus:
    interfaces:
      UpdateOrderStatusUseCase:
  github.com/viniciuscluna/tc-fiap-50/internal/order/presenter:
    interfaces:
      OrderPresenter:
