### Add Product
# @name AddProduct
POST {{baseUrl}}v1/product
Content-Type: application/json

{
  "name": "Pizza",
  "category": 2,
  "price": 10.99,
  "description": "Pizza description",
  "image_link": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
}

### Get Products by Category
# @name GetProductsByCategory
GET {{baseUrl}}v1/product?category=1
Content-Type: application/json

### Update Product
# @name UpdateProduct
PUT {{baseUrl}}/v1/product/4
Content-Type: application/json

{
  "description": "Pizza description updated"
}

### Delete Product
# @name DeleteProduct
DELETE {{baseUrl}}v1/product/3
Content-Type: application/json