// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	commands "github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/commands"
)

// MockUpdateOrderStatusUseCase is an autogenerated mock type for the UpdateOrderStatusUseCase type
type MockUpdateOrderStatusUseCase struct {
	mock.Mock
}

type MockUpdateOrderStatusUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateOrderStatusUseCase) EXPECT() *MockUpdateOrderStatusUseCase_Expecter {
	return &MockUpdateOrderStatusUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockUpdateOrderStatusUseCase) Execute(command *commands.UpdateOrderStatusCommand) error {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*commands.UpdateOrderStatusCommand) error); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateOrderStatusUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateOrderStatusUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.UpdateOrderStatusCommand
func (_e *MockUpdateOrderStatusUseCase_Expecter) Execute(command interface{}) *MockUpdateOrderStatusUseCase_Execute_Call {
	return &MockUpdateOrderStatusUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockUpdateOrderStatusUseCase_Execute_Call) Run(run func(command *commands.UpdateOrderStatusCommand)) *MockUpdateOrderStatusUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.UpdateOrderStatusCommand))
	})
	return _c
}

func (_c *MockUpdateOrderStatusUseCase_Execute_Call) Return(_a0 error) *MockUpdateOrderStatusUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateOrderStatusUseCase_Execute_Call) RunAndReturn(run func(*commands.UpdateOrderStatusCommand) error) *MockUpdateOrderStatusUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateOrderStatusUseCase creates a new instance of MockUpdateOrderStatusUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateOrderStatusUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateOrderStatusUseCase {
	mock := &MockUpdateOrderStatusUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
