// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

type MockHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClient) EXPECT() *MockHTTPClient_Expecter {
	return &MockHTTPClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, url, response
func (_m *MockHTTPClient) Get(ctx context.Context, url string, response interface{}) error {
	ret := _m.Called(ctx, url, response)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, url, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHTTPClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHTTPClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - response interface{}
func (_e *MockHTTPClient_Expecter) Get(ctx interface{}, url interface{}, response interface{}) *MockHTTPClient_Get_Call {
	return &MockHTTPClient_Get_Call{Call: _e.mock.On("Get", ctx, url, response)}
}

func (_c *MockHTTPClient_Get_Call) Run(run func(ctx context.Context, url string, response interface{})) *MockHTTPClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockHTTPClient_Get_Call) Return(_a0 error) *MockHTTPClient_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_Get_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockHTTPClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function with given fields: ctx, url, body, response
func (_m *MockHTTPClient) Post(ctx context.Context, url string, body interface{}, response interface{}) error {
	ret := _m.Called(ctx, url, body, response)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, interface{}) error); ok {
		r0 = rf(ctx, url, body, response)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHTTPClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockHTTPClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - body interface{}
//   - response interface{}
func (_e *MockHTTPClient_Expecter) Post(ctx interface{}, url interface{}, body interface{}, response interface{}) *MockHTTPClient_Post_Call {
	return &MockHTTPClient_Post_Call{Call: _e.mock.On("Post", ctx, url, body, response)}
}

func (_c *MockHTTPClient_Post_Call) Run(run func(ctx context.Context, url string, body interface{}, response interface{})) *MockHTTPClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(interface{}))
	})
	return _c
}

func (_c *MockHTTPClient_Post_Call) Return(_a0 error) *MockHTTPClient_Post_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPClient_Post_Call) RunAndReturn(run func(context.Context, string, interface{}, interface{}) error) *MockHTTPClient_Post_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPClient creates a new instance of MockHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClient {
	mock := &MockHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
