// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/viniciuscluna/tc-fiap-50/internal/order/domain/entities"
	commands "github.com/viniciuscluna/tc-fiap-50/internal/order/usecase/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockGetOrdersUseCase is an autogenerated mock type for the GetOrdersUseCase type
type MockGetOrdersUseCase struct {
	mock.Mock
}

type MockGetOrdersUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetOrdersUseCase) EXPECT() *MockGetOrdersUseCase_Expecter {
	return &MockGetOrdersUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockGetOrdersUseCase) Execute(command *commands.GetOrdersCommand) ([]*entities.OrderEntity, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*entities.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*commands.GetOrdersCommand) ([]*entities.OrderEntity, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(*commands.GetOrdersCommand) []*entities.OrderEntity); ok {
		r0 = rf(command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*commands.GetOrdersCommand) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetOrdersUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetOrdersUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.GetOrdersCommand
func (_e *MockGetOrdersUseCase_Expecter) Execute(command interface{}) *MockGetOrdersUseCase_Execute_Call {
	return &MockGetOrdersUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockGetOrdersUseCase_Execute_Call) Run(run func(command *commands.GetOrdersCommand)) *MockGetOrdersUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.GetOrdersCommand))
	})
	return _c
}

func (_c *MockGetOrdersUseCase_Execute_Call) Return(_a0 []*entities.OrderEntity, _a1 error) *MockGetOrdersUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetOrdersUseCase_Execute_Call) RunAndReturn(run func(*commands.GetOrdersCommand) ([]*entities.OrderEntity, error)) *MockGetOrdersUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetOrdersUseCase creates a new instance of MockGetOrdersUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetOrdersUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetOrdersUseCase {
	mock := &MockGetOrdersUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
