// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/viniciuscluna/tc-fiap-50/internal/order/domain/entities"
)

// MockOrderProductRepository is an autogenerated mock type for the OrderProductRepository type
type MockOrderProductRepository struct {
	mock.Mock
}

type MockOrderProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderProductRepository) EXPECT() *MockOrderProductRepository_Expecter {
	return &MockOrderProductRepository_Expecter{mock: &_m.Mock}
}

// AddOrderProduct provides a mock function with given fields: orderProduct
func (_m *MockOrderProductRepository) AddOrderProduct(orderProduct *entities.OrderProductEntity) error {
	ret := _m.Called(orderProduct)

	if len(ret) == 0 {
		panic("no return value specified for AddOrderProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.OrderProductEntity) error); ok {
		r0 = rf(orderProduct)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderProductRepository_AddOrderProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrderProduct'
type MockOrderProductRepository_AddOrderProduct_Call struct {
	*mock.Call
}

// AddOrderProduct is a helper method to define mock.On call
//   - orderProduct *entities.OrderProductEntity
func (_e *MockOrderProductRepository_Expecter) AddOrderProduct(orderProduct interface{}) *MockOrderProductRepository_AddOrderProduct_Call {
	return &MockOrderProductRepository_AddOrderProduct_Call{Call: _e.mock.On("AddOrderProduct", orderProduct)}
}

func (_c *MockOrderProductRepository_AddOrderProduct_Call) Run(run func(orderProduct *entities.OrderProductEntity)) *MockOrderProductRepository_AddOrderProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.OrderProductEntity))
	})
	return _c
}

func (_c *MockOrderProductRepository_AddOrderProduct_Call) Return(_a0 error) *MockOrderProductRepository_AddOrderProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderProductRepository_AddOrderProduct_Call) RunAndReturn(run func(*entities.OrderProductEntity) error) *MockOrderProductRepository_AddOrderProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderProductRepository creates a new instance of MockOrderProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderProductRepository {
	mock := &MockOrderProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
