// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/viniciuscluna/tc-fiap-50/internal/order/domain/entities"
)

// MockOrderStatusRepository is an autogenerated mock type for the OrderStatusRepository type
type MockOrderStatusRepository struct {
	mock.Mock
}

type MockOrderStatusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderStatusRepository) EXPECT() *MockOrderStatusRepository_Expecter {
	return &MockOrderStatusRepository_Expecter{mock: &_m.Mock}
}

// AddOrderStatus provides a mock function with given fields: orderStatus
func (_m *MockOrderStatusRepository) AddOrderStatus(orderStatus *entities.OrderStatusEntity) error {
	ret := _m.Called(orderStatus)

	if len(ret) == 0 {
		panic("no return value specified for AddOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.OrderStatusEntity) error); ok {
		r0 = rf(orderStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderStatusRepository_AddOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrderStatus'
type MockOrderStatusRepository_AddOrderStatus_Call struct {
	*mock.Call
}

// AddOrderStatus is a helper method to define mock.On call
//   - orderStatus *entities.OrderStatusEntity
func (_e *MockOrderStatusRepository_Expecter) AddOrderStatus(orderStatus interface{}) *MockOrderStatusRepository_AddOrderStatus_Call {
	return &MockOrderStatusRepository_AddOrderStatus_Call{Call: _e.mock.On("AddOrderStatus", orderStatus)}
}

func (_c *MockOrderStatusRepository_AddOrderStatus_Call) Run(run func(orderStatus *entities.OrderStatusEntity)) *MockOrderStatusRepository_AddOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.OrderStatusEntity))
	})
	return _c
}

func (_c *MockOrderStatusRepository_AddOrderStatus_Call) Return(_a0 error) *MockOrderStatusRepository_AddOrderStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderStatusRepository_AddOrderStatus_Call) RunAndReturn(run func(*entities.OrderStatusEntity) error) *MockOrderStatusRepository_AddOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderStatus provides a mock function with given fields: orderId
func (_m *MockOrderStatusRepository) GetOrderStatus(orderId uint) (*entities.OrderStatusEntity, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderStatus")
	}

	var r0 *entities.OrderStatusEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.OrderStatusEntity, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.OrderStatusEntity); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.OrderStatusEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderStatusRepository_GetOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderStatus'
type MockOrderStatusRepository_GetOrderStatus_Call struct {
	*mock.Call
}

// GetOrderStatus is a helper method to define mock.On call
//   - orderId uint
func (_e *MockOrderStatusRepository_Expecter) GetOrderStatus(orderId interface{}) *MockOrderStatusRepository_GetOrderStatus_Call {
	return &MockOrderStatusRepository_GetOrderStatus_Call{Call: _e.mock.On("GetOrderStatus", orderId)}
}

func (_c *MockOrderStatusRepository_GetOrderStatus_Call) Run(run func(orderId uint)) *MockOrderStatusRepository_GetOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOrderStatusRepository_GetOrderStatus_Call) Return(_a0 *entities.OrderStatusEntity, _a1 error) *MockOrderStatusRepository_GetOrderStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderStatusRepository_GetOrderStatus_Call) RunAndReturn(run func(uint) (*entities.OrderStatusEntity, error)) *MockOrderStatusRepository_GetOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderStatusRepository creates a new instance of MockOrderStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderStatusRepository {
	mock := &MockOrderStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
