// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	clients "github.com/viniciuscluna/tc-fiap-50/internal/infrastructure/clients"

	mock "github.com/stretchr/testify/mock"
)

// MockProductClient is an autogenerated mock type for the ProductClient type
type MockProductClient struct {
	mock.Mock
}

type MockProductClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductClient) EXPECT() *MockProductClient_Expecter {
	return &MockProductClient_Expecter{mock: &_m.Mock}
}

// GetProduct provides a mock function with given fields: ctx, productID
func (_m *MockProductClient) GetProduct(ctx context.Context, productID uint) (*clients.ProductDTO, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *clients.ProductDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*clients.ProductDTO, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *clients.ProductDTO); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients.ProductDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductClient_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type MockProductClient_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uint
func (_e *MockProductClient_Expecter) GetProduct(ctx interface{}, productID interface{}) *MockProductClient_GetProduct_Call {
	return &MockProductClient_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, productID)}
}

func (_c *MockProductClient_GetProduct_Call) Run(run func(ctx context.Context, productID uint)) *MockProductClient_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockProductClient_GetProduct_Call) Return(_a0 *clients.ProductDTO, _a1 error) *MockProductClient_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductClient_GetProduct_Call) RunAndReturn(run func(context.Context, uint) (*clients.ProductDTO, error)) *MockProductClient_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProducts provides a mock function with given fields: ctx, productIDs
func (_m *MockProductClient) GetProducts(ctx context.Context, productIDs []uint) ([]*clients.ProductDTO, error) {
	ret := _m.Called(ctx, productIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 []*clients.ProductDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]*clients.ProductDTO, error)); ok {
		return rf(ctx, productIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []*clients.ProductDTO); ok {
		r0 = rf(ctx, productIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*clients.ProductDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, productIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductClient_GetProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProducts'
type MockProductClient_GetProducts_Call struct {
	*mock.Call
}

// GetProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - productIDs []uint
func (_e *MockProductClient_Expecter) GetProducts(ctx interface{}, productIDs interface{}) *MockProductClient_GetProducts_Call {
	return &MockProductClient_GetProducts_Call{Call: _e.mock.On("GetProducts", ctx, productIDs)}
}

func (_c *MockProductClient_GetProducts_Call) Run(run func(ctx context.Context, productIDs []uint)) *MockProductClient_GetProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockProductClient_GetProducts_Call) Return(_a0 []*clients.ProductDTO, _a1 error) *MockProductClient_GetProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductClient_GetProducts_Call) RunAndReturn(run func(context.Context, []uint) ([]*clients.ProductDTO, error)) *MockProductClient_GetProducts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductClient creates a new instance of MockProductClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductClient {
	mock := &MockProductClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
