// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dto "github.com/viniciuscluna/tc-fiap-50/internal/order/infrastructure/api/dto"
)

// MockOrderController is an autogenerated mock type for the OrderController type
type MockOrderController struct {
	mock.Mock
}

type MockOrderController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderController) EXPECT() *MockOrderController_Expecter {
	return &MockOrderController_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: addOrderRequest
func (_m *MockOrderController) Add(addOrderRequest *dto.AddOrderDto) (string, error) {
	ret := _m.Called(addOrderRequest)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*dto.AddOrderDto) (string, error)); ok {
		return rf(addOrderRequest)
	}
	if rf, ok := ret.Get(0).(func(*dto.AddOrderDto) string); ok {
		r0 = rf(addOrderRequest)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*dto.AddOrderDto) error); ok {
		r1 = rf(addOrderRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderController_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockOrderController_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - addOrderRequest *dto.AddOrderDto
func (_e *MockOrderController_Expecter) Add(addOrderRequest interface{}) *MockOrderController_Add_Call {
	return &MockOrderController_Add_Call{Call: _e.mock.On("Add", addOrderRequest)}
}

func (_c *MockOrderController_Add_Call) Run(run func(addOrderRequest *dto.AddOrderDto)) *MockOrderController_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.AddOrderDto))
	})
	return _c
}

func (_c *MockOrderController_Add_Call) Return(_a0 string, _a1 error) *MockOrderController_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderController_Add_Call) RunAndReturn(run func(*dto.AddOrderDto) (string, error)) *MockOrderController_Add_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: orderId
func (_m *MockOrderController) GetOrder(orderId uint) (*dto.GetOrderResponseDto, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *dto.GetOrderResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*dto.GetOrderResponseDto, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) *dto.GetOrderResponseDto); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrderResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderController_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderController_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - orderId uint
func (_e *MockOrderController_Expecter) GetOrder(orderId interface{}) *MockOrderController_GetOrder_Call {
	return &MockOrderController_GetOrder_Call{Call: _e.mock.On("GetOrder", orderId)}
}

func (_c *MockOrderController_GetOrder_Call) Run(run func(orderId uint)) *MockOrderController_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOrderController_GetOrder_Call) Return(_a0 *dto.GetOrderResponseDto, _a1 error) *MockOrderController_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderController_GetOrder_Call) RunAndReturn(run func(uint) (*dto.GetOrderResponseDto, error)) *MockOrderController_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderStatus provides a mock function with given fields: orderId
func (_m *MockOrderController) GetOrderStatus(orderId uint) (*dto.GetOrderStatusResponseDto, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderStatus")
	}

	var r0 *dto.GetOrderStatusResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*dto.GetOrderStatusResponseDto, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) *dto.GetOrderStatusResponseDto); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrderStatusResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderController_GetOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderStatus'
type MockOrderController_GetOrderStatus_Call struct {
	*mock.Call
}

// GetOrderStatus is a helper method to define mock.On call
//   - orderId uint
func (_e *MockOrderController_Expecter) GetOrderStatus(orderId interface{}) *MockOrderController_GetOrderStatus_Call {
	return &MockOrderController_GetOrderStatus_Call{Call: _e.mock.On("GetOrderStatus", orderId)}
}

func (_c *MockOrderController_GetOrderStatus_Call) Run(run func(orderId uint)) *MockOrderController_GetOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOrderController_GetOrderStatus_Call) Return(_a0 *dto.GetOrderStatusResponseDto, _a1 error) *MockOrderController_GetOrderStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderController_GetOrderStatus_Call) RunAndReturn(run func(uint) (*dto.GetOrderStatusResponseDto, error)) *MockOrderController_GetOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrders provides a mock function with no fields
func (_m *MockOrderController) GetOrders() (*dto.GetOrdersResponseDto, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOrders")
	}

	var r0 *dto.GetOrdersResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func() (*dto.GetOrdersResponseDto, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *dto.GetOrdersResponseDto); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetOrdersResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderController_GetOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrders'
type MockOrderController_GetOrders_Call struct {
	*mock.Call
}

// GetOrders is a helper method to define mock.On call
func (_e *MockOrderController_Expecter) GetOrders() *MockOrderController_GetOrders_Call {
	return &MockOrderController_GetOrders_Call{Call: _e.mock.On("GetOrders")}
}

func (_c *MockOrderController_GetOrders_Call) Run(run func()) *MockOrderController_GetOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderController_GetOrders_Call) Return(_a0 *dto.GetOrdersResponseDto, _a1 error) *MockOrderController_GetOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderController_GetOrders_Call) RunAndReturn(run func() (*dto.GetOrdersResponseDto, error)) *MockOrderController_GetOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function with given fields: orderId, updateOrderStatusRequest
func (_m *MockOrderController) UpdateOrderStatus(orderId uint, updateOrderStatusRequest *dto.UpdateOrderStatusRequestDto) error {
	ret := _m.Called(orderId, updateOrderStatusRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, *dto.UpdateOrderStatusRequestDto) error); ok {
		r0 = rf(orderId, updateOrderStatusRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderController_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockOrderController_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - orderId uint
//   - updateOrderStatusRequest *dto.UpdateOrderStatusRequestDto
func (_e *MockOrderController_Expecter) UpdateOrderStatus(orderId interface{}, updateOrderStatusRequest interface{}) *MockOrderController_UpdateOrderStatus_Call {
	return &MockOrderController_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", orderId, updateOrderStatusRequest)}
}

func (_c *MockOrderController_UpdateOrderStatus_Call) Run(run func(orderId uint, updateOrderStatusRequest *dto.UpdateOrderStatusRequestDto)) *MockOrderController_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(*dto.UpdateOrderStatusRequestDto))
	})
	return _c
}

func (_c *MockOrderController_UpdateOrderStatus_Call) Return(_a0 error) *MockOrderController_UpdateOrderStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderController_UpdateOrderStatus_Call) RunAndReturn(run func(uint, *dto.UpdateOrderStatusRequestDto) error) *MockOrderController_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderController creates a new instance of MockOrderController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderController {
	mock := &MockOrderController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
